### ISSUE TITLE
RequestTime plugin support.

### ISSUE THREAD

**Issue by yinkh** [tomwojcik/starlette-context#20]
I have develop a web system base on fastapi which use starlette as a basic framework. I wrote a plugin to calculate how much time an request take, here is the code:
```
import time
from typing import Union

from starlette.requests import Request
from starlette.responses import Response

from starlette_context.plugins.plugin import Plugin
from starlette_context import _request_scope_context_storage


class RequestTimePlugin(Plugin):
    key = "X-Request-Time"

    async def process_request(self, request: Request) -> Union[str, int, dict, float]:
        """
        Runs always on request.
        Extracts value from header by default.
        """
        assert isinstance(self.key, str)
        return time.time()

    async def enrich_response(self, response: Response) -> None:
        context: dict = _request_scope_context_storage.get()
        start_time = context.get(self.key)
        context[self.key] = time.time() - start_time
        _request_scope_context_storage.set(context)

```
the problem is i want request-id and request-time can be logging inside request_access log,but when the access log is print ,the whole dispatch function is finished.I notice you have reset the contextvar at the bottom of dispatch function.So the code for access log:
```
class RequestAccessFormatter(AccessFormatter):
    def __init__(self, fmt=None, datefmt=None, style="%", use_colors=None):
        super().__init__(fmt=fmt, datefmt=datefmt, style=style)
        self.use_colors = False

    def get_status_code(self, record):
        status_code = record.__dict__["status_code"]
        return status_code

    def get_request_time(self):
        return round(context.data['X-Request-Time'], 3)

    def get_request_id(self):
        return context.data['X-Request-ID']

    def get_user_agent(self, scope):
        user_agent = '-'
        for header_name, header_value in scope.get("headers", []):
            if 'user-agent' in str(header_name):
                user_agent = header_value
                break
        return user_agent

    def formatMessage(self, record):
        record_copy = copy(record)
        # user_agent = self.get_user_agent(scope)
        request_time = self.get_request_time()
        request_id = self.get_request_id()

        # record_copy.__dict__['user_agent'] = user_agent
        record_copy.__dict__['request_time'] = request_time
        record_copy.__dict__['request_id'] = request_id
        return super().formatMessage(record_copy)
```
will get the error:

```
  File "D:\py_workspace\demo\common\log_handler.py", line 56, in formatMessage
    request_time = self.get_request_time()
  File "D:\py_workspace\demo\common\log_handler.py", line 40, in get_request_time
    return context.data['X-Request-Time']
  File "D:\py_workspace\demo\venv\lib\site-packages\starlette_context\ctx.py", line 28, in data
    raise RuntimeError(
RuntimeError: You didn't use ContextMiddleware or you're trying to access `context` object outside of the request-response cycle.
```

I have two solution for this, one is not reset contextvar at bottom of dispatch function,the other way is copy contextvar to request.scope, which one is better? I you think one of this way is ok, i will pull a PR to support RequestTime.

Access log format will be something like:
```
ACCESS_LOG_FORMAT = '[%(asctime)s] %(request_id)s %(status_code)s %(request_time)ss %(client_addr)s ' \
                    '- "%(request_line)s"'
```
`[2020-09-30 11:45:28,769] 678bba8a5a754d41928135b468171ddc 200 0.008s 172.37.2.55:49921 - "PUT /api/xxx/xxxx/xxxx HTTP/1.1"`

**Comment by tomwojcik** [comment]
The order of middlewares in your app is important. Try to add it as the first one if possible, so it will also be executed as the last one on the response and that's when the context is emptied. The exception here says the context is not available because it's not running in the request-response cycle. Probably it happens when your create a "response" log. And indeed, it's not possible to access context there as it's emptied and I will keep it like that to make sure there's no memory leak.

Sadly, it's not possible to access context data on the "response" log. Or at least not to my knowledge.

What I'd suggest:
- in your logger check if context exists (`` if context.exists()``). If not, don't log context data
- add "logger" on another application layer, so the server doesn't have to time it, but rather the gateway/proxy would be responsible for that


I don't understand why you're doing all those things here

```
    async def enrich_response(self, response: Response) -> None:
        context: dict = _request_scope_context_storage.get()
        start_time = context.get(self.key)
        context[self.key] = time.time() - start_time
        _request_scope_context_storage.set(context)
```

In this method you're supposed to alter the response. If you want to change something in the context, this line is sufficient 

```context[self.key] = time.time() - start_time```

``_request_scope_context_storage.set`` is private for a reason. The idea is to use the ``context`` object directly. Did you have a problem with ``from starlette_context import context`` this context? Have you seen the [docs](https://starlette-context.readthedocs.io/en/latest/context.html)?

Plugins are used to extract some data from the request, keep it in the ``context`` and add some data to the response.
What you rather want is to alter the ``set_context`` method in your middleware. You can add a timestamp in this method and in logs just ``time.time() - context['timestamp']`` and all logs would have diff that's incrementing. The ``set_context`` method is in the middleware. Just remember to check if context is available.

I'd advise to use ``HeaderKeys`` class instead of raw strings to access headers.

**Comment by yinkh** [comment]
Thanks for your reply, the reason of calculate request time inside `enrich_response` method is if an error occor then two logger(access_log and error_log) is need to rewrite. I will try the method you said.
