### ISSUE TITLE
How to use context in Jinja (or any other template engine)?

### ISSUE THREAD

**Issue by mrk24251** [tomwojcik/starlette-context#48]
How can i use my created context in template globally?
I know that we can do it by adding context in each @app.rout separately but I want to show context in base template and it is really meaningless to add context for each route for this purpose.

**Comment by hhamana** [comment]
First, just to make sure there is no misunderstanding. The context offered by starlette-context is a [ContextVars](https://docs.python.org/3/library/contextvars.html) used to keep track of variables in an async environnment, here more specifically in a Starlette endpoint. Jinja also has something called a [Context](https://jinja2docs.readthedocs.io/en/stable/api.html#the-context) which is entirely different and unrelated, although its purpose is somewhat similar: Jinja's context is for passing data (and functions) to the template.
If your question is essentially "how to use the Jinja context", please have a look at the Jinja documentation.

Now, if your question is how to take data from the starlette context to the Jinja context, I guess we can talk.
You probably don't want to to include the context as argument for each route, it is indeed meaningless at best, if it even works (I don't think you can, but I haven't tried, because I don't see why you'd do that anyway).
You should use the `ContextMiddleware` or `RawContextMiddleware` to initialize and use the context, and then `from starlette_context import context` can work as a top-level import, which will be valid for anything within the request-response cycle. I assume your template would be for an HTML response, which is appropriate.

There really is nothing special to it, passing data to jinja can be done as usual with keyword arguments or a dict. You need to take take the data from the starlette_context you need, and then pass it around to Jinja.
```
from starlette_context import context


# jinja template creation omitted
data_in_context = context.get('my_key')
rendered = template.render(data=data_in_context)
```
Adapt to whatever custom use you're doing with Jinja.
