### ISSUE TITLE
uninitialized context access raises LookupError

### ISSUE THREAD

**Issue by dmig-alarstudios** [tomwojcik/starlette-context#7]
Here is a testcase:
```
>>> from starlette_context import context
>>> context
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmig/.pyenv/versions/3.8.2/lib/python3.8/collections/__init__.py", line 1014, in __repr__
    def __repr__(self): return repr(self.data)
  File "/home/dmig/.pyenv/versions/marty-services-3.8.2/lib/python3.8/site-packages/starlette_context/ctx.py", line 26, in data
    return _request_scope_context_storage.get()
LookupError: <ContextVar name='starlette_context' at 0x7f3b3be81c20>
```

**Comment by dmig-alarstudios** [comment]
I expected to get nothing here

**Comment by tomwojcik** [comment]
If you got this error, it means context wasn't initialized in the middleware. If you use this middleware and didn't set anything, it will return an empty context.

If that's not the case, please share your code with me.

Here I test your error https://github.com/tomwojcik/starlette-context/blob/master/tests/test_integration/test_context_no_middleware.py


If you try to access `context` outside of request-response scope it might not work as it is destroyed when the response is created.

**Comment by dmig-alarstudios** [comment]
My case is third: I tried to access context outside of the request-response cycle. During another middleware install.

**Comment by VukW** [comment]
I've also get the third case, but i want to use context optionally, only if it already exists.
Are the any ways to check if context is already available?

**Comment by tomwojcik** [comment]
1. If you want to use it in another middleware, it needs to be added after the `ContextMiddleware` is added to the asgi app. For example request/response logger.
2. If you want to access it in a route, it will always be available as all requests that hit routes are 'past middlewares'.
3. If you access it outside of the request-response cycle, it will **never** be available, as we use this new pythonic `ContextVar` and that's how this thing works.

I think that's the price you need to pay for using asgi apps. You can't rely on threads and that's the beauty/ugly of using async code.

Therefore, even if there is an option to check if it's available, it makes no sense to implement it as you either use it properly or not.

**Comment by VukW** [comment]
Sorry if I've described not enough clearly
I want to use context in the function that may be called outside of any request.
If my function is called inside request, I want to get request-id (using your cool RequestIdPlugin) and use it somehow. However, if there is no request, and no any context - I want just to execute all my another staff, context absence is not a problem for that case.

Now I've used just try-except:
```
request_id is None
try:
  request_id = context.data['X-Request-ID']
except RuntimeError:
   pass
```

but I'll be glad to use any explicit check instead of catching a whole class of RuntimeErrors , like this:
```
request_id = None
if context_exist():
   request_id = ...
```

**Comment by tomwojcik** [comment]
I still don't understand what is the case when that'd be useful and when one might now know whether context is available or not but I will implement this. Makes sense to have it instead of try/except. 
Will do that over the weekend. Thanks for reporting this feature request.

Also, I tried to mimic `dict` as much as possible. The only thing you can't do with context, is unpack it with `**context`. All other `dict` operations like `context['X-Request-ID']` should work without accessing `.data` property directly. 

But whatever fits you best : )

**Comment by VukW** [comment]
Thank you for merging!
I'm sorry I've not implemented tests by myself, by some unknown reasons I was not successful in running tests on my machine.

Also, thank you for the package, it is as simple as useful for me:)
